# Lab | Pandas

In this lab, we will be working with the customer data from an insurance company, which can be found in the CSV file located at the following link: https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

The data includes information such as customer ID, state, gender, education, income, and other variables that can be used to perform various analyses.

Throughout the lab, we will be using the pandas library in Python to manipulate and analyze the data. Pandas is a powerful library that provides various data manipulation and analysis tools, including the ability to load and manipulate data from a variety of sources, including CSV files.

### Data Description

- Customer - Customer ID

- ST - State where customers live

- Gender - Gender of the customer

- Education - Background education of customers 

- Customer Lifetime Value - Customer lifetime value(CLV) is the total revenue the client will derive from their entire relationship with a customer. In other words, is the predicted or calculated value of a customer over their entire duration as a policyholder with the insurance company. It is an estimation of the net profit that the insurance company expects to generate from a customer throughout their relationship with the company. Customer Lifetime Value takes into account factors such as the duration of the customer's policy, premium payments, claim history, renewal likelihood, and potential additional services or products the customer may purchase. It helps insurers assess the long-term profitability and value associated with retaining a particular customer.

- Income - Customers income

- Monthly Premium Auto - Amount of money the customer pays on a monthly basis as a premium for their auto insurance coverage. It represents the recurring cost that the insured person must pay to maintain their insurance policy and receive coverage for potential damages, accidents, or other covered events related to their vehicle.

- Number of Open Complaints - Number of complaints the customer opened

- Policy Type - There are three type of policies in car insurance (Corporate Auto, Personal Auto, and Special Auto)

- Vehicle Class - Type of vehicle classes that customers have Two-Door Car, Four-Door Car SUV, Luxury SUV, Sports Car, and Luxury Car

- Total Claim Amount - the sum of all claims made by the customer. It represents the total monetary value of all approved claims for incidents such as accidents, theft, vandalism, or other covered events.

External Resources: https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9

In [1]:
import pandas as pd

url = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv"

insurance_df = pd.read_csv(url)

df_clean = insurance_df.dropna(how='all').copy()

df_clean = df_clean.set_index('Customer')

## Challenge 1: Understanding the data

In this challenge, you will use pandas to explore a given dataset. Your task is to gain a deep understanding of the data by analyzing its characteristics, dimensions, and statistical properties.

- Identify the dimensions of the dataset by determining the number of rows and columns it contains.

In [2]:
df_clean.shape

(1071, 10)

- Determine the data types of each column and evaluate whether they are appropriate for the nature of the variable. You should also provide suggestions for fixing any incorrect data types.

In [3]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1071 entries, RB50392 to MY31220
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ST                         1071 non-null   object
 1   GENDER                     954 non-null    object
 2   Education                  1071 non-null   object
 3   Customer Lifetime Value    1068 non-null   object
 4   Income                     1071 non-null   float64
 5   Monthly Premium Auto       1071 non-null   float64
 6   Number of Open Complaints  1071 non-null   object
 7   Policy Type                1071 non-null   object
 8   Vehicle Class              1071 non-null   object
 9   Total Claim Amount         1071 non-null   float64
dtypes: float64(3), object(7)
memory usage: 92.0+ KB

- Modifying Customer Lifetime Value to float replacing % with nothing and dividing by 100

In [4]:
df_clean['Customer Lifetime Value'] = df_clean['Customer Lifetime Value'].str.replace('%', '').astype(float) / 100

- Modifying Number of Open complaints to integer replacing / with nothing

In [5]:
df_clean["Number of Open Complaints"] = df_clean["Number of Open Complaints"].str.replace("/","").astype(int)

- Replace missing values in categorical columns with 'Unknown'

In [6]:
text_cols = df_clean.select_dtypes(include='object').columns
df_clean[text_cols] = df_clean[text_cols].fillna('Unknown')

In [7]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1071 entries, RB50392 to MY31220
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ST                         1071 non-null   object
 1   GENDER                     1071 non-null   object
 2   Education                  1071 non-null   object
 3   Customer Lifetime Value    1068 non-null   float64
 4   Income                     1071 non-null   float64
 5   Monthly Premium Auto       1071 non-null   float64
 6   Number of Open Complaints  1071 non-null   int64
 7   Policy Type                1071 non-null   object
 8   Vehicle Class              1071 non-null   object
 9   Total Claim Amount         1071 non-null   float64
dtypes: float64(4), int64(1), object(5)
memory usage: 92.0+ KB

- Cleaning categorical values to ensure consistency.

In [8]:
df_clean['GENDER'] = df_clean['GENDER'].str.replace('Male', 'M').str.replace('female', 'F').str.replace('Femal', 'F')
df_clean['ST'] = df_clean['ST'].str.replace('WA', 'Washington').str.replace('AZ', 'Arizona')
df_clean['Education'] = df_clean['Education'].str.replace('Bachelors', 'Bachelor')

- Identify the number of unique values for each column and determine which columns appear to be categorical.

In [9]:
categorical_cols = df_clean.select_dtypes(include='object')
categorical_cols.nunique()

ST               6
GENDER           3
Education        5
Policy Type      3
Vehicle Class    6
dtype: int64

- You should also describe the unique values of each categorical column and the range of values for numerical columns, and give your insights.

In [10]:
df_clean[["ST"]].value_counts()

ST
Oregon        320
Arizona       211
California    211
Cali          120
Washington    111
Nevada         98
Name: count, dtype: int64

In [11]:
df_clean[["GENDER"]].value_counts()

GENDER
F          502
M          452
Unknown    117
Name: count, dtype: int64

In [12]:
df_clean[["Education"]].value_counts()

Education
Bachelor                331
College                 313
High School or Below    296
Master                   94
Doctor                   37
Name: count, dtype: int64

In [13]:
df_clean[["Policy Type"]].value_counts()

Policy Type
Personal Auto     780
Corporate Auto    234
Special Auto       57
Name: count, dtype: int64

In [14]:
df_clean[["Vehicle Class"]].value_counts()

Vehicle Class
Four-Door Car    576
Two-Door Car     205
SUV              199
Sports Car        57
Luxury SUV        20
Luxury Car        14
Name: count, dtype: int64

- You should also describe the range of values for numerical columns, and give your insights.

In [15]:
numerical_cols = df_clean.select_dtypes(include='number').nunique()
for col in numerical_cols.index:
    print(f"{col}: min={df_clean[col].min()}, max={df_clean[col].max()}")

Customer Lifetime Value: min=2004.3507, max=58166.553499999995
Income: min=0.0, max=99960.0
Monthly Premium Auto: min=61.0, max=35354.0
Number of Open Complaints: min=1000, max=1500
Total Claim Amount: min=0.382107, max=2893.239678

- Compute summary statistics such as mean, median, mode, standard deviation, and quartiles to understand the central tendency and distribution of the data for numerical columns. You should also provide your conclusions based on these summary statistics.

In [16]:
df_clean.describe()

,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Total Claim Amount
count,1068.000000,1071.000000,1071.000000,1071.000000,1071.000000
mean,7936.902593,39295.701214,193.234360,1039.402428,404.986909
std,6434.784103,30469.427060,1601.190369,88.376941,293.027260
min,2004.350700,0.000000,61.000000,1000.000000,0.382107
25%,4034.079950,14072.000000,68.000000,1000.000000,202.157702
50%,5881.742350,36234.000000,83.000000,1000.000000,354.729129
75%,8962.871975,64631.000000,109.500000,1000.000000,532.800000
max,58166.553500,99960.000000,35354.000000,1500.000000,2893.239678

- Compute summary statistics for categorical columns and providing your conclusions based on these statistics.

In [17]:
for col in categorical_cols:
    print(f"Columna: {col}")
    print(df_clean[col].value_counts())
    print("\n")

Columna: ST
ST
Oregon        320
Arizona       211
California    211
Cali          120
Washington    111
Nevada         98
Name: count, dtype: int64


Columna: GENDER
GENDER
F          502
M          452
Unknown    117
Name: count, dtype: int64


Columna: Education
Education
Bachelor                331
College                 313
High School or Below    296
Master                   94
Doctor                   37
Name: count, dtype: int64


Columna: Policy Type
Policy Type
Personal Auto     780
Corporate Auto    234
Special Auto       57
Name: count, dtype: int64


Columna: Vehicle Class
Vehicle Class
Four-Door Car    576
Two-Door Car     205
SUV              199
Sports Car        57
Luxury SUV        20
Luxury Car        14
Name: count, dtype: int64

## Challenge 2: analyzing the data

### Exercise 1

The marketing team wants to know the top 5 less common customer locations. Create a pandas Series object that contains the customer locations and their frequencies, and then retrieve the top 5 less common locations in ascending order.

In [18]:
customer_locations = pd.Series(df_clean['ST'])
customer_locations.value_counts().sort_values(ascending=True).head(5)

ST
Nevada         98
Washington    111
Cali          120
Arizona       211
California    211
Name: count, dtype: int64

### Exercise 2

The sales team wants to know the total number of policies sold for each type of policy. Create a pandas Series object that contains the policy types and their total number of policies sold, and then retrieve the policy type with the highest number of policies sold.

*Hint:*
- *Using value_counts() method simplifies this analysis.*
- *Futhermore, there is a method that returns the index of the maximum value in a column or row.*

In [19]:
policies = pd.Series(df_clean['Policy Type'])
policies.value_counts().idxmax()

'Personal Auto'

### Exercise 3

The sales team wants to know if customers with Personal Auto have a lower income than those with Corporate Auto. How does the average income compare between the two policy types?

- Use *loc* to create two dataframes: one containing only Personal Auto policies and one containing only Corporate Auto policies.
- Calculate the average income for each policy.
- Print the results.

In [20]:
corporate_mean_income = df_clean.loc[df_clean['Policy Type'] == 'Corporate Auto', 'Income'].mean()
personal_mean_income = df_clean.loc[df_clean['Policy Type'] == 'Personal Auto', 'Income'].mean()
if corporate_mean_income > personal_mean_income:
    mean_incomes_diff = corporate_mean_income - personal_mean_income
    print(f"Corporate Auto mean income: {corporate_mean_income:.2f}")
    print(f"Personal Auto mean income: {personal_mean_income:.2f}")
    print(f"Corporate Auto mean income is {mean_incomes_diff:.2f} higher than Personal Auto's")
elif personal_mean_income > corporate_mean_income:
    mean_incomes_diff = personal_mean_income - corporate_mean_income
    print(f"Corporate Auto mean income:{corporate_mean_income:.2f}")
    print(f"Personal Auto mean income:{personal_mean_income:.2f}")
    print(f"Personal Auto mean income is {mean_incomes_diff:.2f} higher than Corporate Auto's")
else:
    print(f"Corporate Auto and Personal Auto have the same mean income")

Corporate Auto mean income: 41390.31
Personal Auto mean income: 38180.70
Corporate Auto mean income is 3209.61 higher than Personal Auto's

### Bonus: Exercise 4

Your goal is to identify customers with a high policy claim amount.

Instructions:

- Review again the statistics for total claim amount to gain an understanding of the data.
- To identify potential areas for improving customer retention and profitability, we want to focus on customers with a high policy claim amount. Consider customers with a high policy claim amount to be those in the top 25% of the total claim amount. Create a pandas DataFrame object that contains information about customers with a policy claim amount greater than the 75th percentile.
- Use DataFrame methods to calculate summary statistics about the high policy claim amount data.

*Note: When analyzing data, we often want to focus on certain groups of values to gain insights. Percentiles are a useful tool to help us define these groups. A percentile is a measure that tells us what percentage of values in a dataset are below a certain value. For example, the 75th percentile represents the value below which 75% of the data falls. Similarly, the 25th percentile represents the value below which 25% of the data falls. When we talk about the top 25%, we are referring to the values that fall above the 75th percentile, which represent the top quarter of the data. On the other hand, when we talk about the bottom 25%, we are referring to the values that fall below the 25th percentile, which represent the bottom quarter of the data. By focusing on these groups, we can identify patterns and trends that may be useful for making decisions and taking action.*

*Hint: look for a method that gives you the percentile or quantile 0.75 and 0.25 for a Pandas Series.*

*Hint 2: check `Boolean selection according to the values of a single column` in https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9*

In [21]:
df_clean[["Total Claim Amount"]].quantile(0.75)

Total Claim Amount    532.8
Name: 0.75, dtype: float64

In [22]:
claim_75quantile = df_clean.loc[df_clean["Total Claim Amount"] >= 532.80, :]
claim_75quantile

,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
Customer,,,,,,,,,,
QZ44356,Arizona,F,Bachelor,6979.5359,0.0,94.0,1000,Personal Auto,Four-Door Car,1131.464935
AI49188,Nevada,F,Bachelor,12887.4317,48767.0,108.0,1000,Personal Auto,Two-Door Car,566.472247
OE15005,Cali,Unknown,College,3945.2416,28855.0,101.0,1000,Personal Auto,SUV,647.442031
TZ98966,Nevada,Unknown,Bachelor,2450.1910,0.0,73.0,1300,Corporate Auto,Four-Door Car,554.376763
US89481,California,Unknown,Bachelor,3946.3721,0.0,111.0,1000,Personal Auto,Four-Door Car,799.200000
...,...,...,...,...,...,...,...,...,...,...
YG44474,Oregon,M,College,14014.7213,54193.0,117.0,1000,Corporate Auto,SUV,720.752945
RY92647,Cali,F,Bachelor,10506.7717,0.0,92.0,1000,Personal Auto,Four-Door Car,546.524896
GS98873,Arizona,F,Bachelor,3239.1247,16061.0,88.0,1000,Personal Auto,Four-Door Car,633.600000
CW49887,California,F,Master,4626.8011,79487.0,114.0,1000,Special Auto,SUV,547.200000
MY31220,California,F,College,8997.0402,54230.0,112.0,1000,Personal Auto,Two-Door Car,537.600000